[package]
name = "mathlib-nursery"
version = "0.1"
lean_version = "leanprover-community/lean:3.19.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "0b4444ca1870767f085b439903676f7cbfe0fbf8"}
